env:
  DOCKER_COMPOSE_VERSION: 3.7.0

services:
  - docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  # This should be docker-build, but we need local npm modules because right now
  # coveralls will NOT sync up if coverage report is run inside docker.
  - make docker-dev
  - sleep 10
  - make docker-up
  - sleep 30
  - docker ps -a

script:
  - make docker-test
  - cd application && npm run coveralls-script

notifications:
  slack: libellis:7v5cSuqlayq37v0Qaeyrvbg7
