env:
  DOCKER_COMPOSE_VERSION: 3.7.0

services:
  - docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - make docker-build
  - sleep 10
  - docker ps -a

script:
  - make docker-test

notifications:
  slack: libellis:7v5cSuqlayq37v0Qaeyrvbg7
